### ISSUE TITLE
User Switching Plugin

### ISSUE THREAD

**Issue by salcode** [burbswp/five-minute-presentations#1]
I'd enjoy hearing someone do a five-minute presentation on the [User Switching](https://wordpress.org/plugins/user-switching/) plugin

**Comment by lepittenger** [comment]
+1 such a handy plugin

**Comment by itsjusteileen** [comment]
- this plugin is genius when testing in a multisite

**Comment by JPry** [comment]
I could do this one @liamdempsey

**Comment by liamdempsey** [comment]
@JPry: Are you up for delivering a 5-min talk on Monday, 19-Sep-2016? Please note, it's the third Monday of the month.

**Comment by JPry** [comment]
@liamdempsey Sounds good, I can do that!

**Comment by liamdempsey** [comment]
Thanks, @JPry! I'll update the meetup page.

**Comment by salcode** [comment]
This presentation was nicely presented at https://www.meetup.com/philly-burbs-wordpress-meetup/events/233540434/ by @JPry
