### ISSUE TITLE
Best Practices for QR Codes

### ISSUE THREAD

**Issue by salcode** [burbswp/five-minute-presentations#12]
While I don't find QR codes useful in many situations.  There are occasions where they are (or clients really want them).

Over time, I've found some helpful techniques when creating them and I think it would make a good 5 min presentation.

![qrcode](https://cloud.githubusercontent.com/assets/5194588/18479050/789c5236-79a1-11e6-8172-bd9647839881.png)

(useless example QR code that points to this issue #12)

**Comment by lepittenger** [comment]
Ha! Love the example. +1 vote for this topic. I've never used QR codes before. Cringe emoji.

**Comment by angelinasimms** [comment]
I've heard some interesting horror stories on QR Codes gone WRONG! I noticed that the updated version of the Nike Run Club app has a QR code available for when users visit Nike Running stores. I've only used a QR code once (2009, maybe 2010??) and I was not impressed.

**Comment by field1post** [comment]
I used to use QR codes on the back of my business cards so individuals could get to my site from the business card. I noticed very little increase in mobile traffic as a result.  However, they certainly have their place as door placards at brick and mortar establishments as well as printed coupons.

**Comment by JPry** [comment]
@salcode I think you can mark this completed now 😉

**Comment by salcode** [comment]
This presentation was given at https://www.meetup.com/philly-burbs-wordpress-meetup/events/233540434/

**Comment by liamdempsey** [comment]
Nice one, @salcode!
