### ISSUE TITLE
Creating a Custom Theme Options Page

### ISSUE THREAD

**Issue by mattnye** [burbswp/five-minute-presentations#19]
Would be happy to give this talk if there's any interest. I'm sure this is something everyone uses daily and already has built, but might be a good talk for someone not familiar. I've seen about 7 billion variations on the Theme Options page in my years managing WP sites. Seems like no two are the same, actually. I've used some really slick ones but have also seen some really bad UX practices.

Talk could be a quick overview of what this page is and how to implement your own, and then some components I've built to help streamline site builds.

**Comment by liamdempsey** [comment]
Great job on this talk, Matt! Thanks again.
