### ISSUE TITLE
Why use add_query_arg() ?

### ISSUE THREAD

**Issue by salcode** [burbswp/five-minute-presentations#21]
I think a nice 5 minute talk could be why to use `add_query_arg()`.

It seems easy enough to add a URL parameter with something like:

```
echo $url . '?mycolor=red';
```

Why use  [add_query_arg()](https://developer.wordpress.org/reference/functions/add_query_arg/) ?

**Comment by liamdempsey** [comment]
That works for me. Are you suggesting that you'd be up for giving that tonight please?

**Comment by salcode** [comment]
Yes, it would be my pleasure. 👍

**Comment by liamdempsey** [comment]
Great job, Sal! Thanks for stepping in at last minute and bringing such quality. Excellent stuff, friend.

**Comment by salcode** [comment]
Thanks for the kind words @liamdempsey 

I'm closing this issue, but for possible future reference:

- here are my slides: [Why Use add_query_arg()](https://ironcodestudio.com/presentations/why-use-add-query-arg/) 
- this 5 minute talk was given on [2017-04-10](https://www.meetup.com/philly-burbs-wordpress-meetup/events/238517918/)
