### ISSUE TITLE
Gravatar

### ISSUE THREAD

**Issue by salcode** [burbswp/five-minute-presentations#8]
I think Gravatar would make a great 5 minute presentation.  I was working with WordPress for a long time until I learned about it.

If you don't know about Gravatar but want to so you can give the presentation, [WPBeginner's article on gravatar](http://www.wpbeginner.com/beginners-guide/what-is-gravatar-and-why-you-should-start-using-it-right-away/) is a great place to start.

**Comment by angelinasimms** [comment]
I'd like to claim this one.

**Comment by liamdempsey** [comment]
Wanna give that talk on this upcoming Monday night?

**Comment by itsjusteileen** [comment]
Which one? Name change or ticketing?

**Comment by liamdempsey** [comment]
Hi Eileen - I was asking Angelina if she wanted to talk about Gravatars.

**Comment by angelinasimms** [comment]
Okay.

**Comment by salcode** [comment]
Hey fellow Burbsians,

Just a quick GitHub Tip, when communicating to someone(s) specific it is helpful to use their username(s) prefixed with an '@' sign.

e.g.

> @angelinasimms I'm sorry I'll miss this presentation

This is helpful for two reasons:
1.  If the person is not already following the thread, they'll get a notification
2.  It helps clarify to whom the message is directed

Of course, sometimes you don't want to target anyone, which is fine too.

e.g.

> This is a great topic, I'd like to hear about this too.

**Comment by salcode** [comment]
Now that this topic is scheduled, I'm going to mark this issue **closed**. 👍
